# Generated by Django 2.2 on 2019-04-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(null=True)),
                ('uploaded', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('method', models.IntegerField(choices=[(0, 'Manual'), (1, 'Automatic'), (2, 'Confirmed')], null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Category')),
            ],
        ),
    ]
